### ISSUE TITLE
Unable to get Video as a Viewer

### ISSUE THREAD

**Issue by Dev-Ayan-Dasgupta** [adityathakurxd/flutter-live#1]
When we try to join as a viewer, we are unable to get a video of the broadcaster. 
`remoteTrack` is returned as null, and I can only see **No Video** being displayed on my screen.

**Comment by adityathakurxd** [comment]
Hi, I have only added the viewer functionality recently, and might need some fixes. 
I recommend instead checking out the example app in 100ms-flutter [here](https://github.com/100mslive/100ms-flutter/tree/main/example). It has the [hls_viewer](https://github.com/100mslive/100ms-flutter/tree/main/example/lib/hls_viewer) code you can refer.

**Comment by Dev-Ayan-Dasgupta** [comment]
Thank you, I have referred to the latest version of your project and am able to view a session. Cheers.
