### ISSUE TITLE
App crashes in iOS simulator and Devices.

### ISSUE THREAD

**Issue by Dev-Ayan-Dasgupta** [adityathakurxd/flutter-live#3]
When we run the app and try to navigate to the viewer screen or live streaming screen, the app immediately crashes with the following error:

![hms_ios_issue](https://user-images.githubusercontent.com/107356140/219619688-9e81be42-88cd-4c2b-b2c8-5caac4466446.jpeg)

Could you please test it on your end and let me know what's causing the issue?

Cheers.

**Comment by Decoder07** [comment]
Hi @Dev-Ayan-Dasgupta can you try this : 

`hmsSDK.startHlsStreaming(hmshlsConfig: null);`

**Comment by Dev-Ayan-Dasgupta** [comment]
@Decoder07 tried this but still receiving the same error as before.

> Hi @Dev-Ayan-Dasgupta can you try this :
> 
> `hmsSDK.startHlsStreaming(hmshlsConfig: null);`

**Comment by Decoder07** [comment]
Can you switch the `hmssdk_flutter` package to this branch : https://github.com/100mslive/100ms-flutter/tree/develop
 
 If it doesn't work let's get on a call, You can book a slot here: https://calendly.com/pushpam-saxena/30min

**Comment by Dev-Ayan-Dasgupta** [comment]
@Decoder07 I switched the package to the branch you mentioned but still facing the same error and the app crashes.

**Comment by Decoder07** [comment]
This should have worked. Let's get on a call if you are available.

**Comment by Dev-Ayan-Dasgupta** [comment]
Sure, I booked a call for 3 PM on calendly.

**Comment by Decoder07** [comment]
@Dev-Ayan-Dasgupta have sent you an email can you please check it?

**Comment by Dev-Ayan-Dasgupta** [comment]
Closing this issue as we were missing microphone and camera permissions in Info.plist.

**Comment by adityathakurxd** [comment]
I have updated the `inflo.plist` with the camera and microphone permissions. Sorry about not having them setup before.
