### ISSUE TITLE
class join service use it create token but it use in HMSConfig config that time not working.

### ISSUE THREAD

**Issue by nirajakbari44** [adityathakurxd/flutter-live#6]
D/InitService(12307): fetchInitConfig: response=Response{protocol=h2, code=401, message=, url=https://prod-init.100ms.live/init?user_agent_v2=os%3Aandroid%2Cos_version%3A22%2Csdk%3Aandroid%2Csdk_version%3A2.5.7%2Cdevice_model%3Avivo_V3%2Cenv%3Adebug%2Cframework%3Aflutter%2Cframework_version%3A2.18.5%2Cframework_sdk_version%3A1.3.0}
D/HMSTransport(12307): internalConnect:: failed ❌ [error=HTTPError: Bad Request [code=401, action=INIT, description=Received , cause=null]]
D/PerformanceJoinEvents(12307): Sending event: 48 {time=48, init_response_time=43, is_preview_called=false}
D/AnalyticsEventsService(12307): AnalyticsEvent(name=join.failure, level=ERROR, includesPII=false, properties={init_response_time=43, time=48, is_preview_called=false}) queued

**Comment by adityathakurxd** [comment]
Hi, looks like there is some issue with the token as "Error: token is empty" is the message.

Were you able to setup the project on dashboard (following this tutorial https://youtu.be/GJ94-BaszpQ) and replace the roomid and Token endpoint in `join_service.dart file`, with your roomId and your token endpoint (as obtained by the steps mentioned in the video above)?

```
String roomId = "<Your Room ID>";
Uri endPoint = Uri.parse(
        "<Token endpoint>/api/token");
```
Don't forget to append `/api/token` at the end of your Token endpoint.

**Comment by nirajakbari44** [comment]
ok its working

**Comment by adityathakurxd** [comment]
Awesome! Closing this issue then.
